services:
  twitch-notifier:
    build: .
    container_name: twitch-notifier
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./state.json:/app/state.json
    ports:
      - "3000:3000"

