services:
  twitch-notifier:
    build: .
    container_name: twitch-notifier
    restart: unless-stopped
    user: "${UID}:${GID}"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "3001:3001"

